/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_INT32, .range_min = -100, .range_max = 100, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.demand_pct" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.error" },
	{ .id = 2, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.setback_active" },
	{ .id = 3, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "energy.rate_peak" },
	{ .id = 4, .type = ARBITER_FACT_INT32, .range_min = -400, .range_max = 500, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "outdoor.temp_c" },
	{ .id = 5, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "schedule.occupied_hours" },
	{ .id = 6, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 60000, .safety_relevant = false, .name = "zone.humidity_pct" },
	{ .id = 7, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "zone.occupancy" },
	{ .id = 8, .type = ARBITER_FACT_INT32, .range_min = 150, .range_max = 300, .default_value = 220, .stale_after_ms = 0, .safety_relevant = false, .name = "zone.setpoint_c" },
	{ .id = 9, .type = ARBITER_FACT_INT32, .range_min = -200, .range_max = 600, .default_value = 0, .stale_after_ms = 30000, .safety_relevant = false, .name = "zone.temp_c" },
	{ .id = 10, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "zone.window_open" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 10, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 10, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 10, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GT, .value = 50, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GT, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 10, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_LT, .value = -5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 10, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_GT, .value = 65, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GE, .value = -5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_LE, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GE, .value = -5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_LE, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_LE, .value = 65, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 10, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "hvac_off" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "run_compressor" },
	{ .id = 2, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "run_dehumidifier" },
	{ .id = 3, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "run_heater" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_CONSTRAINT, .condition_start = 0, .condition_count = 1, .action_start = 0, .action_count = 1, .expr_start = 0, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 6, .safety_critical = false, .name = "01_window.open", .explanation = "Window open — HVAC off to save energy." },
	{ .id = 1, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 1, .condition_count = 3, .action_start = 0, .action_count = 0, .expr_start = 1, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = 5, .safety_critical = false, .name = "05_setback", .explanation = "Unoccupied & off-schedule — setback mode." },
	{ .id = 2, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 4, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 3, .expr_count = 3, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "10_compute.error", .explanation = NULL },
	{ .id = 3, .rule_class = ARBITER_RULE_CONSTRAINT, .condition_start = 5, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 6, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 4, .safety_critical = false, .name = "15_peak.shed", .explanation = "Peak pricing — limiting demand to 50%." },
	{ .id = 4, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 7, .condition_count = 2, .action_start = 3, .action_count = 1, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "20_mode.heating", .explanation = "Heating demand > 5%." },
	{ .id = 5, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 9, .condition_count = 2, .action_start = 1, .action_count = 1, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "21_mode.cooling", .explanation = "Cooling demand > 5%." },
	{ .id = 6, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 11, .condition_count = 3, .action_start = 2, .action_count = 1, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = false, .name = "22_mode.dehumidify", .explanation = "Humidity > 65% and no temp demand — dehumidify." },
	{ .id = 7, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 14, .condition_count = 4, .action_start = 0, .action_count = 0, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = false, .name = "23_mode.idle", .explanation = NULL },
};

static const struct ARBITER_expr_def model_expressions[] = {
	{ .target_fact_id = 0, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 1, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 8, .op = ARBITER_EXPR_SUB, .left_fact_id = 8, .left_literal = 0, .right_fact_id = 65535, .right_literal = 30, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_SUB, .left_fact_id = 8, .left_literal = 0, .right_fact_id = 9, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_SCALE, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 65535, .right_literal = 100, .scale = 50 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_CLAMP, .left_fact_id = 0, .left_literal = 0, .right_fact_id = 65535, .right_literal = -100, .scale = 100 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_CLAMP, .left_fact_id = 0, .left_literal = 0, .right_fact_id = 65535, .right_literal = -50, .scale = 50 },
};

static const char *model_mode_names[] = {
	"mode.cooling",
	"mode.dehumidify",
	"mode.heating",
	"mode.idle",
	"mode.peak_shed",
	"mode.setback",
	"mode.window_override",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "hvac_zone_controller",
	.model_hash = { 0xab, 0xbb, 0x7c, 0x5a, 0xc3, 0xc5, 0xfb, 0xbd, 0xe9, 0xcb, 0x71, 0x8d, 0x47, 0x35, 0x03, 0x8d, 0x10, 0x97, 0x48, 0x6b, 0xe5, 0x21, 0xa9, 0x28, 0x8f, 0xb9, 0x6e, 0x4a, 0xf4, 0x92, 0x27, 0x40 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 11,
	.rule_count = 8,
	.condition_count = 18,
	.action_count = 4,
	.expr_count = 7,
	.mode_count = 7,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.expressions = model_expressions,
	.mode_names = model_mode_names,
};
