/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "in.enable" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = -500000, .range_max = 500000, .default_value = 0, .stale_after_ms = 100, .safety_relevant = true, .name = "in.measurement" },
	{ .id = 2, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "in.sensor_valid" },
	{ .id = 3, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.correction" },
	{ .id = 4, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.denom" },
	{ .id = 5, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.innovation" },
	{ .id = 6, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 1000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.k_gain" },
	{ .id = 7, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 10000, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.p_est" },
	{ .id = 8, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.p_factor" },
	{ .id = 9, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.p_pred" },
	{ .id = 10, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.x_est" },
	{ .id = 11, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "kf.x_pred" },
	{ .id = 12, .type = ARBITER_FACT_INT32, .range_min = 1, .range_max = 100000, .default_value = 100, .stale_after_ms = 0, .safety_relevant = false, .name = "param.q" },
	{ .id = 13, .type = ARBITER_FACT_INT32, .range_min = 1, .range_max = 500000, .default_value = 5000, .stale_after_ms = 0, .safety_relevant = false, .name = "param.r" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_STALE, .value = 100, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "publish_estimate" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 0, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = true, .name = "01_fault.sensor", .explanation = "Sensor fault — hold last estimate." },
	{ .id = 1, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 2, .condition_count = 1, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "02_check.disabled", .explanation = NULL },
	{ .id = 2, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 3, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = false, .name = "10_predict", .explanation = "Predict: propagate state and covariance." },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 5, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "20_update.gain", .explanation = "Update: compute Kalman gain." },
	{ .id = 4, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 7, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "30_update.state", .explanation = "Update: correct state estimate and covariance." },
	{ .id = 5, .rule_class = ARBITER_RULE_OBLIGATION, .condition_start = 9, .condition_count = 1, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "40_output", .explanation = "Publish filtered estimate." },
};

static const char *model_mode_names[] = {
	"mode.idle",
	"mode.running",
	"mode.sensor_fault",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "kalman_filter",
	.model_hash = { 0x10, 0x02, 0x58, 0x54, 0xfc, 0x10, 0x21, 0x0c, 0x74, 0x4c, 0x80, 0xb0, 0xbd, 0xbd, 0xdb, 0xe7, 0xf9, 0x00, 0xa3, 0x07, 0xd0, 0xb3, 0x6c, 0x33, 0x65, 0xa4, 0xde, 0x27, 0x3a, 0x5c, 0xb1, 0xcb },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 14,
	.rule_count = 6,
	.condition_count = 10,
	.action_count = 1,
	.mode_count = 3,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.mode_names = model_mode_names,
};
