# SPDX-License-Identifier: MIT
"""C source and header emitter for compiled ARB models."""

from __future__ import annotations

from .canonical import CanonicalModel

# --- Header includes for state machine support ---
_STATE_HEADER_INCLUDE = '#include <arbiter/arbiter_state.h>'

_OP_MAP = {
    "==": "ARBITER_OP_EQ", "!=": "ARBITER_OP_NE",
    "<": "ARBITER_OP_LT", "<=": "ARBITER_OP_LE",
    ">": "ARBITER_OP_GT", ">=": "ARBITER_OP_GE",
    "in": "ARBITER_OP_IN", "not_in": "ARBITER_OP_NOT_IN",
    "stale": "ARBITER_OP_STALE", "not_stale": "ARBITER_OP_NOT_STALE",
    "changed": "ARBITER_OP_CHANGED",
    "delta_gt": "ARBITER_OP_DELTA_GT", "delta_lt": "ARBITER_OP_DELTA_LT",
}

_TYPE_MAP = {
    "bool": "ARBITER_FACT_BOOL", "int32": "ARBITER_FACT_INT32",
    "uint32": "ARBITER_FACT_UINT32", "enum": "ARBITER_FACT_ENUM",
}

_CLASS_MAP = {
    "inference": "ARBITER_RULE_INFERENCE", "constraint": "ARBITER_RULE_CONSTRAINT",
    "mode_guard": "ARBITER_RULE_MODE_GUARD", "safety_guard": "ARBITER_RULE_SAFETY_GUARD",
    "obligation": "ARBITER_RULE_OBLIGATION", "advisory": "ARBITER_RULE_ADVISORY",
}

_ACTION_TYPE_MAP = {
    "callback": "ARBITER_ACTION_CALLBACK", "log": "ARBITER_ACTION_LOG",
    "notify": "ARBITER_ACTION_NOTIFY", "set_fact": "ARBITER_ACTION_SET_FACT",
    "set_mode": "ARBITER_ACTION_SET_MODE",
    "raise_fault": "ARBITER_ACTION_RAISE_FAULT", "clear_fault": "ARBITER_ACTION_CLEAR_FAULT",
}

_EXPR_OP_MAP = {
    "add": "ARBITER_EXPR_ADD", "sub": "ARBITER_EXPR_SUB",
    "mul": "ARBITER_EXPR_MUL", "div": "ARBITER_EXPR_DIV",
    "mod": "ARBITER_EXPR_MOD", "abs": "ARBITER_EXPR_ABS",
    "negate": "ARBITER_EXPR_NEGATE", "min": "ARBITER_EXPR_MIN",
    "max": "ARBITER_EXPR_MAX", "clamp": "ARBITER_EXPR_CLAMP",
    "shift_r": "ARBITER_EXPR_SHIFT_R", "shift_l": "ARBITER_EXPR_SHIFT_L",
    "scale": "ARBITER_EXPR_SCALE", "accumulate": "ARBITER_EXPR_ACCUMULATE",
    "assign": "ARBITER_EXPR_ASSIGN",
}


def _compute_rule_dep_masks(model: CanonicalModel) -> list[int]:
    """Compute a uint64 bitmask of fact IDs each rule depends on."""
    masks: list[int] = []
    cond_offset = 0
    for r in model.rules:
        when = r.get("when", {})
        cond_count = 0
        if isinstance(when, dict):
            for gk in ("all", "any", "not"):
                g = when.get(gk)
                if isinstance(g, list):
                    cond_count += len(g)
        mask = 0
        for ci in range(cond_offset, cond_offset + cond_count):
            if ci < len(model.conditions):
                fid = model.conditions[ci].get("fact_id", 0)
                if fid < 64:
                    mask |= 1 << fid
        masks.append(mask)
        cond_offset += cond_count
    return masks


def _compute_required_mode(
    rule: dict,
    model: CanonicalModel,
) -> str:
    """Return the C literal for required_mode.

    For mode_guard rules whose 'when' block contains an equality check
    on a fact named 'mode' (or similar mode fact), extract the mode value.
    Otherwise return UINT16_MAX (any mode).
    """
    if rule.get("class") != "mode_guard":
        return "UINT16_MAX"

    when = rule.get("when", {})
    if not isinstance(when, dict):
        return "UINT16_MAX"

    # Scan all condition groups for mode equality checks
    for gk in ("all", "any"):
        group = when.get(gk)
        if not isinstance(group, list):
            continue
        for cond in group:
            if not isinstance(cond, dict):
                continue
            fact_name = cond.get("fact", "")
            op = cond.get("op", "")
            # Look for mode facts by checking if the fact name contains 'mode'
            if "mode" in fact_name.lower() and op == "==":
                val = cond.get("value")
                if isinstance(val, int):
                    return str(val)
                # Value might be a mode name string
                if isinstance(val, str) and val in model.mode_id_map:
                    return str(model.mode_id_map[val])
    return "UINT16_MAX"


def _c_str(s: str | None) -> str:
    return f'"{s}"' if s else "NULL"


def _c_bool(v: bool) -> str:
    return "true" if v else "false"


def emit_c_header(model: CanonicalModel, emit_trace_strings: bool = True) -> str:
    """Generate the C header file for a compiled ARB model."""
    lines = [
        "/* SPDX-License-Identifier: MIT */",
        "/* AUTO-GENERATED by arbiterc — do not edit */",
        "",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <arbiter/arbiter_model.h>",
        "",
        f'#define ARBITER_MODEL_NAME "{model.name}"',
        f'#define ARBITER_MODEL_HASH "{model.model_hash}"',
        f"#define ARBITER_MODEL_FACT_COUNT {model.max_facts}u",
        f"#define ARBITER_MODEL_RULE_COUNT {model.max_rules}u",
        f"#define ARBITER_MODEL_CONDITION_COUNT {model.max_conditions}u",
        f"#define ARBITER_MODEL_ACTION_COUNT {model.max_actions}u",
        f"#define ARBITER_MODEL_MAX_FACTS {model.max_facts}u",
        f"#define ARBITER_MODEL_MAX_RULES {model.max_rules}u",
        f"#define ARBITER_MODEL_MAX_CONDITIONS {model.max_conditions}u",
        f"#define ARBITER_MODEL_MAX_ACTIONS {model.max_actions}u",
        f"#define ARBITER_MODEL_WCET_OP_COUNT {model.max_rules + model.max_conditions}u",
        f"#define ARBITER_MODEL_TRACE_CAPACITY {model.max_rules}u",
        "",
        "extern const struct ARBITER_model ARBITER_generated_model;",
        "",
    ]

    # Emit fact index defines
    for fid, idx in model.fact_id_map.items():
        safe_name = fid.replace(".", "_").upper()
        lines.append(f"#define ARBITER_FACT_{safe_name} {idx}u")

    lines.append("")

    # Emit mode index defines
    for mid, idx in model.mode_id_map.items():
        safe_name = mid.replace(".", "_").upper()
        lines.append(f"#define ARBITER_MODE_{safe_name} {idx}u")

    lines.append("")

    # Per-rule dependency bitmasks for dirty-flag rule skip
    rule_dep_masks = _compute_rule_dep_masks(model)
    if rule_dep_masks:
        lines.append("/* Per-rule input fact dependency bitmasks (dirty-flag skip). */")
        mask_strs = [f"UINT64_C(0x{m:016x})" for m in rule_dep_masks]
        lines.append(
            "#define ARBITER_MODEL_RULE_DEPS { "
            + ", ".join(mask_strs)
            + " }"
        )
        lines.append("")

    # State defines (REQ-ARCH-039)
    states = getattr(model, "states", [])
    if states:
        lines.append(_STATE_HEADER_INCLUDE)
        lines.append("")
        lines.append(f"#define ARBITER_MODEL_STATE_COUNT {len(states)}u")
        transitions = getattr(model, "transitions", [])
        lines.append(f"#define ARBITER_MODEL_TRANSITION_COUNT {len(transitions)}u")
        lines.append("")
        for st in states:
            safe_name = st["id"].replace(".", "_").upper()
            lines.append(f"#define ARBITER_STATE_{safe_name} {st['index']}u")
        lines.append("")
        lines.append("extern const struct ARBITER_state_def ARBITER_generated_states[];")
        lines.append("extern const struct ARBITER_transition_def ARBITER_generated_transitions[];")
        lines.append("")

    return "\n".join(lines)


def emit_c_source(model: CanonicalModel, header_name: str = "arbiter_model.h",
                  emit_trace_strings: bool = True) -> str:
    """Generate the C source file for a compiled ARB model."""
    lines = [
        "/* SPDX-License-Identifier: MIT */",
        "/* AUTO-GENERATED by arbiterc — do not edit */",
        "",
        f'#include "{header_name}"',
        "#include <arbiter/arbiter.h>",
        "",
    ]

    # Facts table
    lines.append("static const struct ARBITER_fact_def model_facts[] = {")
    for i, f in enumerate(model.facts):
        rng = f.get("range", [0, 0])
        rmin = rng[0] if isinstance(rng, list) and len(rng) >= 2 else 0
        rmax = rng[1] if isinstance(rng, list) and len(rng) >= 2 else 0
        name = _c_str(f["id"]) if emit_trace_strings else "NULL"
        lines.append(
            f"\t{{ .id = {i}, .type = {_TYPE_MAP.get(f.get('type', 'bool'), 'ARBITER_FACT_BOOL')}, "
            f".range_min = {rmin}, .range_max = {rmax}, "
            f".default_value = {f.get('default', 0)}, "
            f".stale_after_ms = {f.get('stale_after_ms', 0)}, "
            f".safety_relevant = {_c_bool(f.get('safety_relevant', False))}, "
            f".name = {name} }},"
        )
    lines.append("};")
    lines.append("")

    # Conditions table
    lines.append("static const struct ARBITER_condition_def model_conditions[] = {")
    group_enum = {"all": "ARBITER_COND_ALL", "any": "ARBITER_COND_ANY", "not": "ARBITER_COND_NOT"}
    for i, c in enumerate(model.conditions):
        op_enum = _OP_MAP.get(c.get("op", "=="), "ARBITER_OP_EQ")
        grp = group_enum.get(c.get("group", "all"), "ARBITER_COND_ALL")
        val = c.get("value", 0)
        if isinstance(val, bool):
            val = 1 if val else 0
        lines.append(
            f"\t{{ .fact_id = {c.get('fact_id', 0)}, .op = {op_enum}, "
            f".value = {val}, .group = {grp}, "
            f".group_index = 0, .next = UINT16_MAX }},"
        )
    if not model.conditions:
        lines.append("\t{ 0 },  /* empty */")
    lines.append("};")
    lines.append("")

    # Actions table
    lines.append("static const struct ARBITER_action_def model_actions[] = {")
    for i, a in enumerate(model.actions):
        atype = _ACTION_TYPE_MAP.get(a.get("type", "callback"), "ARBITER_ACTION_CALLBACK")
        name = _c_str(a["id"]) if emit_trace_strings else "NULL"
        lines.append(
            f"\t{{ .id = {i}, .type = {atype}, "
            f".target_fact_id = 0, .target_value = 0, "
            f".callback = NULL, "
            f".must_complete_within_ms = {a.get('must_complete_within_ms', 0)}, "
            f".safe_state_action = {_c_bool(a.get('safe_state_action', False))}, "
            f".name = {name} }},"
        )
    if not model.actions:
        lines.append("\t{ 0 },  /* empty */")
    lines.append("};")
    lines.append("")

    # Rules table
    lines.append("static const struct ARBITER_rule_def model_rules[] = {")
    cond_offset = 0
    for i, r in enumerate(model.rules):
        rclass = _CLASS_MAP.get(r.get("class", "inference"), "ARBITER_RULE_INFERENCE")
        then = r.get("then", {})
        set_mode = "UINT16_MAX"
        if isinstance(then, dict) and "set_mode" in then:
            mid = model.mode_id_map.get(then["set_mode"])
            if mid is not None:
                set_mode = str(mid)

        # Count conditions for this rule
        when = r.get("when", {})
        cond_count = 0
        if isinstance(when, dict):
            for gk in ("all", "any", "not"):
                g = when.get(gk)
                if isinstance(g, list):
                    cond_count += len(g)

        action_start = 0
        action_count = 0
        if isinstance(then, dict) and "action" in then:
            aid = model.action_id_map.get(then["action"])
            if aid is not None:
                action_start = aid
                action_count = 1

        safety_critical = _c_bool(
            isinstance(then, dict) and then.get("criticality") == "safety_critical"
        )
        name = _c_str(r["id"]) if emit_trace_strings else "NULL"
        raw_expl = then.get("explanation") if isinstance(then, dict) else None
        explanation = _c_str(raw_expl) if emit_trace_strings else "NULL"

        expr_start = r.get("_expr_start", 0)
        expr_count = r.get("_expr_count", 0)

        # Mode-aware pruning: mode_guard rules with a mode equality check
        required_mode = _compute_required_mode(r, model)

        lines.append(
            f"\t{{ .id = {i}, .rule_class = {rclass}, "
            f".condition_start = {cond_offset}, .condition_count = {cond_count}, "
            f".action_start = {action_start}, .action_count = {action_count}, "
            f".expr_start = {expr_start}, .expr_count = {expr_count}, "
            f".safety_goal_id = UINT16_MAX, .set_mode = {set_mode}, "
            f".required_mode = {required_mode}, "
            f".safety_critical = {safety_critical}, "
            f".name = {name}, .explanation = {explanation} }},"
        )
        cond_offset += cond_count

    if not model.rules:
        lines.append("\t{ 0 },  /* empty */")
    lines.append("};")
    lines.append("")

    # Expressions table — only emit the array when there are entries.
    # Never emit a pointer variable: a pointer's value is not a constant
    # expression in C, so it cannot be used in a static struct initializer.
    expressions = getattr(model, "expressions", [])
    if expressions:
        lines.append("static const struct ARBITER_expr_def model_expressions[] = {")
        for e in expressions:
            op_enum = _EXPR_OP_MAP.get(e.get("op", "assign"), "ARBITER_EXPR_ASSIGN")
            lines.append(
                f"\t{{ .target_fact_id = {e['target_fact_id']}, "
                f".op = {op_enum}, "
                f".left_fact_id = {e['left_fact_id']}, "
                f".left_literal = {e['left_literal']}, "
                f".right_fact_id = {e['right_fact_id']}, "
                f".right_literal = {e['right_literal']}, "
                f".scale = {e['scale']} }},"
            )
        lines.append("};")
        lines.append("")
    # If no expressions, we emit nothing here and use NULL directly below.

    # Mode names
    if model.modes and emit_trace_strings:
        lines.append("static const char *model_mode_names[] = {")
        for m in model.modes:
            if isinstance(m, dict) and "id" in m:
                lines.append(f'\t"{m["id"]}",')
        lines.append("};")
    else:
        lines.append("static const char **model_mode_names = NULL;")
    lines.append("")

    # Model hash bytes
    hash_hex = model.model_hash[:64].ljust(64, "0")
    hash_bytes = ", ".join(f"0x{hash_hex[j:j+2]}" for j in range(0, 64, 2))
    schema_hex = model.schema_hash[:64].ljust(64, "0")
    schema_bytes = ", ".join(f"0x{schema_hex[j:j+2]}" for j in range(0, 64, 2))

    expr_count_total = len(getattr(model, "expressions", []))
    exprs_field = "model_expressions" if expressions else "NULL"
    lines.extend([
        "const struct ARBITER_model ARBITER_generated_model = {",
        f'\t.name = "{model.name}",',
        f"\t.model_hash = {{ {hash_bytes} }},",
        f"\t.schema_hash = {{ {schema_bytes} }},",
        f"\t.fact_count = {model.max_facts},",
        f"\t.rule_count = {model.max_rules},",
        f"\t.condition_count = {model.max_conditions},",
        f"\t.action_count = {model.max_actions},",
        f"\t.expr_count = {expr_count_total},",
        f"\t.mode_count = {len([m for m in model.modes if isinstance(m, dict)])},",
        "\t.facts = model_facts,",
        "\t.rules = model_rules,",
        "\t.conditions = model_conditions,",
        "\t.actions = model_actions,",
        f"\t.expressions = {exprs_field},",
        "\t.mode_names = model_mode_names,",
        "};",
        "",
    ])

    # States table (REQ-ARCH-039)
    states = getattr(model, "states", [])
    transitions = getattr(model, "transitions", [])
    if states:
        lines.append("")
        lines.append("const struct ARBITER_state_def ARBITER_generated_states[] = {")
        for st in states:
            name = _c_str(st["id"]) if emit_trace_strings else "NULL"
            lines.append(
                f"\t{{ .id = {st['index']}, "
                f".on_enter_action = {st['on_enter_action']}, "
                f".on_exit_action = {st['on_exit_action']}, "
                f".name = {name} }},"
            )
        lines.append("};")
        lines.append("")

    # Transitions table (REQ-ARCH-039)
    if transitions:
        lines.append("const struct ARBITER_transition_def ARBITER_generated_transitions[] = {")
        for tr in transitions:
            lines.append(
                f"\t{{ .source_state = {tr['source_state']}, "
                f".target_state = {tr['target_state']}, "
                f".condition_start = {tr['condition_start']}, "
                f".condition_count = {tr['condition_count']}, "
                f".guard_start = {tr['guard_start']}, "
                f".guard_count = {tr['guard_count']}, "
                f".priority = {tr['priority']} }},"
            )
        lines.append("};")
        lines.append("")

    return "\n".join(lines)
