/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "bat.soc_pct" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = -200, .range_max = 600, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "bat.temp_c" },
	{ .id = 2, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 60000, .default_value = 0, .stale_after_ms = 500, .safety_relevant = false, .name = "bat.voltage_mv" },
	{ .id = 3, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "mppt.delta_power" },
	{ .id = 4, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "mppt.delta_voltage" },
	{ .id = 5, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 1, .stale_after_ms = 0, .safety_relevant = false, .name = "mppt.direction" },
	{ .id = 6, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 1000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "mppt.duty_pct_x10" },
	{ .id = 7, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "mppt.power_mw" },
	{ .id = 8, .type = ARBITER_FACT_UINT32, .range_min = 1, .range_max = 50, .default_value = 10, .stale_after_ms = 0, .safety_relevant = false, .name = "mppt.step_size" },
	{ .id = 9, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 20000, .default_value = 0, .stale_after_ms = 100, .safety_relevant = false, .name = "pv.current_ma" },
	{ .id = 10, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "pv.prev_power_mw" },
	{ .id = 11, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "pv.prev_voltage_mv" },
	{ .id = 12, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 60000, .default_value = 0, .stale_after_ms = 100, .safety_relevant = false, .name = "pv.voltage_mv" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 12, .op = ARBITER_OP_LT, .value = 5000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_GT, .value = 500, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GE, .value = 95, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_GE, .value = 28400, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 12, .op = ARBITER_OP_GE, .value = 5000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_LT, .value = 95, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_GT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_LT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 12, .op = ARBITER_OP_GE, .value = 5000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = -1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 12, .op = ARBITER_OP_GE, .value = 5000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 12, .op = ARBITER_OP_GE, .value = 5000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = true, .name = "disable_charger" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "set_pwm_duty" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 0, .condition_count = 1, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "01_night", .explanation = "Panel voltage < 5V — night mode, disable converter." },
	{ .id = 1, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 1, .condition_count = 1, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = true, .name = "02_overtemp", .explanation = "Battery > 50°C — stop charging." },
	{ .id = 2, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 2, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = false, .name = "05_float", .explanation = "Battery >= 95% SoC — float charge mode." },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 4, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 5, .safety_critical = false, .name = "10_mppt.compute_power", .explanation = "Compute panel power and deltas for P&O." },
	{ .id = 4, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 6, .condition_count = 1, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "20_mppt.power_increased", .explanation = "Power increased — continue same direction." },
	{ .id = 5, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 7, .condition_count = 1, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "21_mppt.power_decreased", .explanation = "Power decreased — reverse perturb direction." },
	{ .id = 6, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 8, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "30_mppt.step_up", .explanation = NULL },
	{ .id = 7, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 10, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "31_mppt.step_down", .explanation = NULL },
	{ .id = 8, .rule_class = ARBITER_RULE_OBLIGATION, .condition_start = 12, .condition_count = 1, .action_start = 1, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "40_actuate", .explanation = "Apply computed duty cycle to converter PWM." },
};

static const char *model_mode_names[] = {
	"mode.absorb_charge",
	"mode.float_charge",
	"mode.night",
	"mode.overtemp",
	"mode.startup",
	"mode.tracking",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "solar_mppt_tracker",
	.model_hash = { 0x20, 0x7a, 0x75, 0xa0, 0x9c, 0xfb, 0xb9, 0x36, 0x64, 0x96, 0x66, 0xa9, 0xb8, 0xdc, 0xcb, 0x8b, 0x1e, 0xc2, 0xbb, 0xd0, 0x9f, 0x61, 0xa6, 0x82, 0xdf, 0xbd, 0x4f, 0x83, 0x40, 0x99, 0x7a, 0xcb },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 13,
	.rule_count = 9,
	.condition_count = 13,
	.action_count = 2,
	.mode_count = 6,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.mode_names = model_mode_names,
};
