/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.congestion_level" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.link_margin" },
	{ .id = 2, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.parent_score" },
	{ .id = 3, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.should_switch" },
	{ .id = 4, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 255, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "link.alt_route_cost" },
	{ .id = 5, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 32, .default_value = 0, .stale_after_ms = 10000, .safety_relevant = false, .name = "link.neighbor_count" },
	{ .id = 6, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 25500, .default_value = 0, .stale_after_ms = 5000, .safety_relevant = false, .name = "link.parent_lqi" },
	{ .id = 7, .type = ARBITER_FACT_INT32, .range_min = -128, .range_max = 0, .default_value = 0, .stale_after_ms = 5000, .safety_relevant = false, .name = "link.parent_rssi" },
	{ .id = 8, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 255, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "link.route_cost" },
	{ .id = 9, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "node.battery_pct" },
	{ .id = 10, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 511, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "node.child_count" },
	{ .id = 11, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "node.is_leader" },
	{ .id = 12, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "node.is_router" },
	{ .id = 13, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 256, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "queue.depth" },
	{ .id = 14, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 2000000000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "queue.drop_count" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 7, .op = ARBITER_OP_NE, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_LT, .value = 10, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_GT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_LT, .value = 200, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 8, .op = ARBITER_OP_GT, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GT, .value = 75, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GT, .value = 95, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 9, .op = ARBITER_OP_LT, .value = 15, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 12, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_GE, .value = 10, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_LE, .value = 75, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_GT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "drop_low_priority" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "increase_tx_power" },
	{ .id = 2, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "reduce_tx_rate" },
	{ .id = 3, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "request_sleepy" },
	{ .id = 4, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "start_discovery" },
	{ .id = 5, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "switch_parent" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 0, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 0, .expr_count = 6, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "01_compute.link_margin", .explanation = "Compute link margin, parent score, congestion." },
	{ .id = 1, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 1, .condition_count = 1, .action_start = 4, .action_count = 1, .expr_start = 6, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = true, .name = "10_link.isolated", .explanation = "No neighbors — start network discovery." },
	{ .id = 2, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 2, .condition_count = 2, .action_start = 1, .action_count = 1, .expr_start = 6, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = false, .name = "11_link.degraded", .explanation = "Link margin < 10 dB — boost TX power." },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 4, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 6, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "20_route.switch_parent", .explanation = "Alternative parent has significantly better route." },
	{ .id = 4, .rule_class = ARBITER_RULE_OBLIGATION, .condition_start = 6, .condition_count = 1, .action_start = 5, .action_count = 1, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 5, .safety_critical = false, .name = "21_route.do_switch", .explanation = "Initiating parent switch to lower-cost route." },
	{ .id = 5, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 7, .condition_count = 1, .action_start = 2, .action_count = 1, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "30_congestion.high", .explanation = "Queue > 75% — throttle TX rate." },
	{ .id = 6, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 8, .condition_count = 1, .action_start = 0, .action_count = 1, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "31_congestion.critical", .explanation = "Queue > 95% — dropping low-priority frames." },
	{ .id = 7, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 9, .condition_count = 2, .action_start = 3, .action_count = 1, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = false, .name = "40_power.low", .explanation = "Battery < 15% — request sleepy end-device mode." },
	{ .id = 8, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 11, .condition_count = 3, .action_start = 0, .action_count = 0, .expr_start = 7, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 4, .safety_critical = false, .name = "50_nominal", .explanation = "All metrics healthy — nominal operation." },
};

static const struct ARBITER_expr_def model_expressions[] = {
	{ .target_fact_id = 1, .op = ARBITER_EXPR_ADD, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 65535, .right_literal = 100, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_DIV, .left_fact_id = 6, .left_literal = 0, .right_fact_id = 65535, .right_literal = 100, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ACCUMULATE, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 65535, .right_literal = 2, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ACCUMULATE, .left_fact_id = 8, .left_literal = 0, .right_fact_id = 65535, .right_literal = -3, .scale = 1 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_SCALE, .left_fact_id = 13, .left_literal = 0, .right_fact_id = 65535, .right_literal = 100, .scale = 256 },
	{ .target_fact_id = 3, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 3, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 1, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
};

static const char *model_mode_names[] = {
	"mode.congested",
	"mode.degraded_link",
	"mode.isolated",
	"mode.low_power",
	"mode.nominal",
	"mode.parent_search",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "mesh_router_policy",
	.model_hash = { 0x37, 0x86, 0xb3, 0xcf, 0x39, 0x9f, 0x80, 0xc7, 0x33, 0xa3, 0x47, 0x0c, 0x4c, 0xe2, 0x81, 0x6b, 0x91, 0x23, 0xda, 0xd5, 0x44, 0xf2, 0x12, 0x29, 0xbe, 0xa7, 0x11, 0x9f, 0x5c, 0x4f, 0xc5, 0x75 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 15,
	.rule_count = 9,
	.condition_count = 14,
	.action_count = 6,
	.expr_count = 7,
	.mode_count = 6,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.expressions = model_expressions,
	.mode_names = model_mode_names,
};
