/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 10000, .default_value = 800, .stale_after_ms = 0, .safety_relevant = false, .name = "gain.repulse" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 10000, .default_value = 500, .stale_after_ms = 0, .safety_relevant = false, .name = "gain.steer" },
	{ .id = 2, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "in.enable" },
	{ .id = 3, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 360000, .default_value = 0, .stale_after_ms = 50, .safety_relevant = true, .name = "in.heading" },
	{ .id = 4, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "in.pos_x" },
	{ .id = 5, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "in.pos_y" },
	{ .id = 6, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "in.sensor_valid" },
	{ .id = 7, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "nav.distance" },
	{ .id = 8, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "nav.dx" },
	{ .id = 9, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "nav.dy" },
	{ .id = 10, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "nav.heading_error" },
	{ .id = 11, .type = ARBITER_FACT_INT32, .range_min = -1000, .range_max = 1000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "nav.output" },
	{ .id = 12, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "nav.repulsion" },
	{ .id = 13, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "nav.speed_pct" },
	{ .id = 14, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "nav.steer_cmd" },
	{ .id = 15, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 360000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "obs.bearing" },
	{ .id = 16, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 100000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "obs.distance" },
	{ .id = 17, .type = ARBITER_FACT_INT32, .range_min = 50, .range_max = 5000, .default_value = 200, .stale_after_ms = 0, .safety_relevant = false, .name = "param.stop_dist" },
	{ .id = 18, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "wp.x" },
	{ .id = 19, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "wp.y" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 6, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_STALE, .value = 50, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 16, .op = ARBITER_OP_LT, .value = 200, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 16, .op = ARBITER_OP_GE, .value = 200, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_LT, .value = 100, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_GE, .value = 100, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 16, .op = ARBITER_OP_LT, .value = 2000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 16, .op = ARBITER_OP_GE, .value = 200, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_GE, .value = 100, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "halt_motors" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "update_motors" },
	{ .id = 2, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "waypoint_reached" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 0, .condition_count = 2, .action_start = 0, .action_count = 1, .expr_start = 0, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = 5, .safety_critical = true, .name = "01_fault", .explanation = "Sensor fault — halt." },
	{ .id = 1, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 2, .condition_count = 2, .action_start = 0, .action_count = 1, .expr_start = 2, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = true, .name = "02_estop", .explanation = "Obstacle within stop distance — emergency stop." },
	{ .id = 2, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 4, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 4, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "03_idle", .explanation = NULL },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 5, .condition_count = 3, .action_start = 0, .action_count = 0, .expr_start = 4, .expr_count = 4, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = false, .name = "10_delta", .explanation = "Compute vector to waypoint." },
	{ .id = 4, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 8, .condition_count = 2, .action_start = 2, .action_count = 1, .expr_start = 8, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "15_arrived", .explanation = NULL },
	{ .id = 5, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 10, .condition_count = 3, .action_start = 0, .action_count = 0, .expr_start = 10, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "20_steer", .explanation = NULL },
	{ .id = 6, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 13, .condition_count = 3, .action_start = 0, .action_count = 0, .expr_start = 12, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = 4, .safety_critical = false, .name = "25_repulse", .explanation = "Obstacle nearby — apply repulsion." },
	{ .id = 7, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 16, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 14, .expr_count = 4, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "30_output", .explanation = NULL },
	{ .id = 8, .rule_class = ARBITER_RULE_OBLIGATION, .condition_start = 18, .condition_count = 1, .action_start = 1, .action_count = 1, .expr_start = 18, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "40_actuate", .explanation = "Send steering and speed to motors." },
};

static const struct ARBITER_expr_def model_expressions[] = {
	{ .target_fact_id = 11, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 13, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 11, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 13, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 8, .op = ARBITER_EXPR_SUB, .left_fact_id = 18, .left_literal = 0, .right_fact_id = 4, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 9, .op = ARBITER_EXPR_SUB, .left_fact_id = 19, .left_literal = 0, .right_fact_id = 5, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 7, .op = ARBITER_EXPR_ABS, .left_fact_id = 8, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 7, .op = ARBITER_EXPR_ADD, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 9, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 11, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 13, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 10, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 8, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 14, .op = ARBITER_EXPR_SCALE, .left_fact_id = 10, .left_literal = 0, .right_fact_id = 1, .right_literal = 0, .scale = 1000 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_SUB, .left_fact_id = 65535, .left_literal = 2000, .right_fact_id = 16, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_SCALE, .left_fact_id = 12, .left_literal = 0, .right_fact_id = 0, .right_literal = 0, .scale = 2000 },
	{ .target_fact_id = 11, .op = ARBITER_EXPR_SUB, .left_fact_id = 14, .left_literal = 0, .right_fact_id = 12, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 11, .op = ARBITER_EXPR_CLAMP, .left_fact_id = 11, .left_literal = 0, .right_fact_id = 65535, .right_literal = -1000, .scale = 1000 },
	{ .target_fact_id = 13, .op = ARBITER_EXPR_DIV, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 65535, .right_literal = 100, .scale = 1 },
	{ .target_fact_id = 13, .op = ARBITER_EXPR_CLAMP, .left_fact_id = 13, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 100 },
};

static const char *model_mode_names[] = {
	"mode.arrived",
	"mode.estop",
	"mode.idle",
	"mode.navigating",
	"mode.obstacle_close",
	"mode.sensor_fault",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "motion_planner",
	.model_hash = { 0xa6, 0x13, 0xc1, 0xa6, 0xe9, 0xb9, 0xce, 0x8b, 0xa1, 0xd4, 0xe7, 0x2b, 0xed, 0x04, 0x80, 0x02, 0xf8, 0x7e, 0x99, 0xce, 0x03, 0x80, 0x30, 0x1a, 0x23, 0x59, 0x40, 0x3e, 0xb2, 0x09, 0x24, 0x25 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 20,
	.rule_count = 9,
	.condition_count = 19,
	.action_count = 3,
	.expr_count = 18,
	.mode_count = 6,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.expressions = model_expressions,
	.mode_names = model_mode_names,
};
