/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "ch.a_valid" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 50, .safety_relevant = true, .name = "ch.a_value" },
	{ .id = 2, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "ch.b_valid" },
	{ .id = 3, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 50, .safety_relevant = true, .name = "ch.b_value" },
	{ .id = 4, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "ch.c_valid" },
	{ .id = 5, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 50, .safety_relevant = true, .name = "ch.c_value" },
	{ .id = 6, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "vote.ab_agree" },
	{ .id = 7, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "vote.ab_delta" },
	{ .id = 8, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "vote.ac_agree" },
	{ .id = 9, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "vote.ac_delta" },
	{ .id = 10, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "vote.bc_agree" },
	{ .id = 11, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "vote.bc_delta" },
	{ .id = 12, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "vote.result" },
	{ .id = 13, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 100, .stale_after_ms = 0, .safety_relevant = false, .name = "vote.tolerance" },
	{ .id = 14, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 3, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "vote.valid_count" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 13, .op = ARBITER_OP_GT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 14, .op = ARBITER_OP_GE, .value = 2, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_LE, .value = 100, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 9, .op = ARBITER_OP_LE, .value = 100, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 11, .op = ARBITER_OP_LE, .value = 100, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 8, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 14, .op = ARBITER_OP_EQ, .value = 3, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 14, .op = ARBITER_OP_EQ, .value = 2, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 14, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 14, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 10, .safe_state_action = true, .name = "enter_safe_state" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "report_channel_loss" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 0, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 0, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "01_vote.count_valid", .explanation = NULL },
	{ .id = 1, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 1, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 1, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "02_vote.count_a", .explanation = NULL },
	{ .id = 2, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 2, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 2, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "03_vote.count_b", .explanation = NULL },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 3, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 3, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "04_vote.count_c", .explanation = NULL },
	{ .id = 4, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 4, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 4, .expr_count = 6, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "10_vote.deltas", .explanation = NULL },
	{ .id = 5, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 5, .condition_count = 3, .action_start = 0, .action_count = 0, .expr_start = 10, .expr_count = 3, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "20_vote.ab_agree", .explanation = NULL },
	{ .id = 6, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 8, .condition_count = 4, .action_start = 0, .action_count = 0, .expr_start = 13, .expr_count = 3, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "21_vote.ac_agree", .explanation = NULL },
	{ .id = 7, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 12, .condition_count = 5, .action_start = 0, .action_count = 0, .expr_start = 16, .expr_count = 3, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "22_vote.bc_agree", .explanation = NULL },
	{ .id = 8, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 17, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 19, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = false, .name = "30_mode.tmr_ok", .explanation = "All 3 channels valid — full TMR." },
	{ .id = 9, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 18, .condition_count = 1, .action_start = 1, .action_count = 1, .expr_start = 19, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "31_mode.dual", .explanation = "1 channel lost — operating on 2-of-3." },
	{ .id = 10, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 19, .condition_count = 1, .action_start = 1, .action_count = 1, .expr_start = 19, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = true, .name = "32_mode.single", .explanation = "Only 1 valid channel — no voting possible, degraded." },
	{ .id = 11, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 20, .condition_count = 1, .action_start = 0, .action_count = 1, .expr_start = 19, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = true, .name = "33_mode.none", .explanation = "No valid channels — enter safe state." },
};

static const struct ARBITER_expr_def model_expressions[] = {
	{ .target_fact_id = 14, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 14, .op = ARBITER_EXPR_ADD, .left_fact_id = 14, .left_literal = 0, .right_fact_id = 65535, .right_literal = 1, .scale = 1 },
	{ .target_fact_id = 14, .op = ARBITER_EXPR_ADD, .left_fact_id = 14, .left_literal = 0, .right_fact_id = 65535, .right_literal = 1, .scale = 1 },
	{ .target_fact_id = 14, .op = ARBITER_EXPR_ADD, .left_fact_id = 14, .left_literal = 0, .right_fact_id = 65535, .right_literal = 1, .scale = 1 },
	{ .target_fact_id = 7, .op = ARBITER_EXPR_SUB, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 3, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 7, .op = ARBITER_EXPR_ABS, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 9, .op = ARBITER_EXPR_SUB, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 5, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 9, .op = ARBITER_EXPR_ABS, .left_fact_id = 9, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 11, .op = ARBITER_EXPR_SUB, .left_fact_id = 3, .left_literal = 0, .right_fact_id = 5, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 11, .op = ARBITER_EXPR_ABS, .left_fact_id = 11, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 6, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 1, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_ADD, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 3, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_DIV, .left_fact_id = 12, .left_literal = 0, .right_fact_id = 65535, .right_literal = 2, .scale = 1 },
	{ .target_fact_id = 8, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 1, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_ADD, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 5, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_DIV, .left_fact_id = 12, .left_literal = 0, .right_fact_id = 65535, .right_literal = 2, .scale = 1 },
	{ .target_fact_id = 10, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 1, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_ADD, .left_fact_id = 3, .left_literal = 0, .right_fact_id = 5, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_DIV, .left_fact_id = 12, .left_literal = 0, .right_fact_id = 65535, .right_literal = 2, .scale = 1 },
};

static const char *model_mode_names[] = {
	"mode.dual_degraded",
	"mode.no_valid_channel",
	"mode.single_channel",
	"mode.tmr_ok",
	"mode.voter_fault",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "tmr_voter",
	.model_hash = { 0xa2, 0x23, 0x73, 0xb6, 0x1f, 0xd2, 0xbf, 0xa8, 0x53, 0xd9, 0x5b, 0x90, 0x50, 0x47, 0x87, 0x40, 0x32, 0x78, 0xd7, 0x6b, 0x9c, 0xe0, 0xd9, 0x00, 0x3c, 0x77, 0x86, 0x32, 0x16, 0x0d, 0x4b, 0x77 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 15,
	.rule_count = 12,
	.condition_count = 21,
	.action_count = 2,
	.expr_count = 19,
	.mode_count = 5,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.expressions = model_expressions,
	.mode_names = model_mode_names,
};
