/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 10000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "diag0.confidence" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 10000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "diag1.confidence" },
	{ .id = 2, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 10000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "diag2.confidence" },
	{ .id = 3, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 10000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "diag3.confidence" },
	{ .id = 4, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "in.enable" },
	{ .id = 5, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "result.best_confidence" },
	{ .id = 6, .type = ARBITER_FACT_INT32, .range_min = -1, .range_max = 3, .default_value = -1, .stale_after_ms = 0, .safety_relevant = false, .name = "result.diagnosis_id" },
	{ .id = 7, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sym.comm_timeout" },
	{ .id = 8, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "sym.overcurrent" },
	{ .id = 9, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "sym.overtemp" },
	{ .id = 10, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sym.speed_deviation" },
	{ .id = 11, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sym.vibration_high" },
	{ .id = 12, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sym.voltage_sag" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 8, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 9, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 11, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 10, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 12, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_LE, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_GT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "report_diagnosis" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 0, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 0, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "01_idle", .explanation = NULL },
	{ .id = 1, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 1, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 0, .expr_count = 4, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "10_reset", .explanation = NULL },
	{ .id = 2, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 2, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 4, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "20_ev.overcurrent", .explanation = NULL },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 4, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 6, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "21_ev.overtemp", .explanation = NULL },
	{ .id = 4, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 6, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 8, .expr_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "22_ev.vibration", .explanation = NULL },
	{ .id = 5, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 8, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 9, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "23_ev.speed_dev", .explanation = NULL },
	{ .id = 6, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 10, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 11, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "24_ev.voltage_sag", .explanation = NULL },
	{ .id = 7, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 12, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 13, .expr_count = 2, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "25_ev.comm_timeout", .explanation = NULL },
	{ .id = 8, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 14, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 15, .expr_count = 6, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "30_select", .explanation = "Select diagnosis with highest confidence." },
	{ .id = 9, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 15, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 21, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = false, .name = "40_no_fault", .explanation = NULL },
	{ .id = 10, .rule_class = ARBITER_RULE_OBLIGATION, .condition_start = 17, .condition_count = 2, .action_start = 0, .action_count = 1, .expr_start = 21, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = false, .name = "50_report", .explanation = "Report top diagnosis." },
};

static const struct ARBITER_expr_def model_expressions[] = {
	{ .target_fact_id = 0, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 3, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_ADD, .left_fact_id = 0, .left_literal = 0, .right_fact_id = 65535, .right_literal = 400, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ADD, .left_fact_id = 2, .left_literal = 0, .right_fact_id = 65535, .right_literal = 200, .scale = 1 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_ADD, .left_fact_id = 0, .left_literal = 0, .right_fact_id = 65535, .right_literal = 300, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_ADD, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 65535, .right_literal = 350, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_ADD, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 65535, .right_literal = 500, .scale = 1 },
	{ .target_fact_id = 3, .op = ARBITER_EXPR_ADD, .left_fact_id = 3, .left_literal = 0, .right_fact_id = 65535, .right_literal = 450, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_ADD, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 65535, .right_literal = 150, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ADD, .left_fact_id = 2, .left_literal = 0, .right_fact_id = 65535, .right_literal = 500, .scale = 1 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_ADD, .left_fact_id = 0, .left_literal = 0, .right_fact_id = 65535, .right_literal = 100, .scale = 1 },
	{ .target_fact_id = 3, .op = ARBITER_EXPR_ADD, .left_fact_id = 3, .left_literal = 0, .right_fact_id = 65535, .right_literal = 300, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ADD, .left_fact_id = 2, .left_literal = 0, .right_fact_id = 65535, .right_literal = 100, .scale = 1 },
	{ .target_fact_id = 5, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 6, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = -1, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 5, .op = ARBITER_EXPR_MAX, .left_fact_id = 5, .left_literal = 0, .right_fact_id = 0, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 5, .op = ARBITER_EXPR_MAX, .left_fact_id = 5, .left_literal = 0, .right_fact_id = 1, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 5, .op = ARBITER_EXPR_MAX, .left_fact_id = 5, .left_literal = 0, .right_fact_id = 2, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 5, .op = ARBITER_EXPR_MAX, .left_fact_id = 5, .left_literal = 0, .right_fact_id = 3, .right_literal = 0, .scale = 1 },
};

static const char *model_mode_names[] = {
	"mode.analyzing",
	"mode.diagnosed",
	"mode.idle",
	"mode.no_fault",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "fault_diagnosis",
	.model_hash = { 0x1a, 0x61, 0x6e, 0xdd, 0xcd, 0xd6, 0x58, 0x97, 0x60, 0x29, 0xbc, 0x39, 0x4c, 0x08, 0xb7, 0xe0, 0x8e, 0x1c, 0xbd, 0xac, 0x8e, 0x66, 0x03, 0x64, 0x80, 0xa0, 0xa6, 0x5b, 0xe4, 0xb0, 0xb4, 0xf3 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 13,
	.rule_count = 11,
	.condition_count = 19,
	.action_count = 1,
	.expr_count = 21,
	.mode_count = 4,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.expressions = model_expressions,
	.mode_names = model_mode_names,
};
