/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_INT32, .range_min = -3000, .range_max = 3000, .default_value = 0, .stale_after_ms = 500, .safety_relevant = false, .name = "battery.current_ma" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = -40, .range_max = 85, .default_value = 0, .stale_after_ms = 1000, .safety_relevant = false, .name = "battery.temp_c" },
	{ .id = 2, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 5000, .default_value = 0, .stale_after_ms = 500, .safety_relevant = true, .name = "battery.voltage_mv" },
	{ .id = 3, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "charger.enabled" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_LT, .value = 4200, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_LT, .value = 3000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_LT, .value = 3300, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_GT, .value = 60, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_LT, .value = -20, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "disable_charger" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "disable_load" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 0, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 0, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "rule.charging", .explanation = "Charger connected and battery not full." },
	{ .id = 1, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 2, .condition_count = 1, .action_start = 1, .action_count = 1, .expr_start = 0, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = true, .name = "rule.critical_battery", .explanation = "Battery critically low, disabling load." },
	{ .id = 2, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 3, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 0, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "rule.low_battery", .explanation = "Battery voltage below 3.3V threshold." },
	{ .id = 3, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 4, .condition_count = 2, .action_start = 0, .action_count = 1, .expr_start = 0, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 4, .safety_critical = true, .name = "rule.thermal_shutdown", .explanation = "Temperature out of safe range." },
};

static const char *model_mode_names[] = {
	"mode.charging",
	"mode.critical",
	"mode.low_battery",
	"mode.normal",
	"mode.thermal_shutdown",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "battery_policy",
	.model_hash = { 0xfb, 0x6a, 0x01, 0x02, 0x72, 0xec, 0x39, 0x45, 0x91, 0xc0, 0x74, 0xcd, 0x4d, 0x08, 0xdd, 0x8d, 0xa6, 0xa6, 0x89, 0x14, 0x82, 0xbe, 0xd0, 0x2b, 0x0e, 0x83, 0xf9, 0x01, 0xda, 0x48, 0xa8, 0x5a },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 4,
	.rule_count = 4,
	.condition_count = 6,
	.action_count = 2,
	.expr_count = 0,
	.mode_count = 5,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.expressions = NULL,
	.mode_names = model_mode_names,
};
