/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.force_limit_pct" },
	{ .id = 1, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 5000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "calc.speed_limit_mms" },
	{ .id = 2, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.speed_ok" },
	{ .id = 3, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "human.detected" },
	{ .id = 4, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 10000, .default_value = 0, .stale_after_ms = 50, .safety_relevant = true, .name = "human.distance_mm" },
	{ .id = 5, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "robot.enabled" },
	{ .id = 6, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 200, .default_value = 0, .stale_after_ms = 20, .safety_relevant = true, .name = "robot.joint_torque_max_pct" },
	{ .id = 7, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 500, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "robot.payload_kg_x10" },
	{ .id = 8, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 5000, .default_value = 0, .stale_after_ms = 10, .safety_relevant = true, .name = "robot.tcp_speed_mms" },
	{ .id = 9, .type = ARBITER_FACT_ENUM, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "robot.zone" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 9, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 9, .op = ARBITER_OP_EQ, .value = 2, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 9, .op = ARBITER_OP_EQ, .value = 3, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ANY, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_LT, .value = 500, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_LT, .value = 1000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_GE, .value = 500, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 8, .op = ARBITER_OP_GT, .value = 250, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_GT, .value = 80, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 9, .op = ARBITER_OP_EQ, .value = 4, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 10, .safe_state_action = true, .name = "protective_stop" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 0, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "01_zone.free", .explanation = "Free zone, no human — full speed (2000 mm/s)." },
	{ .id = 1, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 2, .condition_count = 1, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 4, .safety_critical = false, .name = "02_zone.reduced", .explanation = "Reduced speed zone — 500 mm/s max." },
	{ .id = 2, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 3, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = false, .name = "03_zone.collaborative", .explanation = "Collaborative zone or human detected — 250 mm/s, 30% force." },
	{ .id = 3, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 5, .condition_count = 2, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = true, .name = "10_proximity.close", .explanation = "Human < 500mm — protective stop." },
	{ .id = 4, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 7, .condition_count = 3, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "11_proximity.near", .explanation = "Human 500-1000mm — speed proportional to distance." },
	{ .id = 5, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 10, .condition_count = 2, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = true, .name = "20_overspeed", .explanation = "TCP speed > limit while human present — stop." },
	{ .id = 6, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 12, .condition_count = 2, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = true, .name = "21_overtorque", .explanation = "Joint torque > 80% rated during collaboration — stop." },
	{ .id = 7, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 14, .condition_count = 1, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = true, .name = "30_zone.stop", .explanation = "Safety zone = STOP." },
};

static const char *model_mode_names[] = {
	"mode.collaborative",
	"mode.estop",
	"mode.full_speed",
	"mode.protective_stop",
	"mode.reduced_speed",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "cobot_safety_controller",
	.model_hash = { 0xd7, 0x5f, 0x86, 0x21, 0x77, 0xec, 0x75, 0xdc, 0x6a, 0x56, 0x7b, 0xbe, 0x67, 0x1f, 0x67, 0xab, 0x16, 0x1c, 0x9e, 0x3b, 0xb6, 0x1c, 0x4b, 0xc7, 0x72, 0xe8, 0x07, 0x06, 0x94, 0x2a, 0xfd, 0x26 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 10,
	.rule_count = 8,
	.condition_count = 15,
	.action_count = 1,
	.mode_count = 5,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.mode_names = model_mode_names,
};
