/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.drain_complete" },
	{ .id = 1, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.fill_complete" },
	{ .id = 2, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "calc.reaction_complete" },
	{ .id = 3, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "proc.abort_cmd" },
	{ .id = 4, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "proc.start_cmd" },
	{ .id = 5, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 10, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "proc.step" },
	{ .id = 6, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 600000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "proc.step_timer_ms" },
	{ .id = 7, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 2000, .safety_relevant = true, .name = "sensor.level_pct" },
	{ .id = 8, .type = ARBITER_FACT_UINT32, .range_min = 0, .range_max = 20000, .default_value = 0, .stale_after_ms = 1000, .safety_relevant = true, .name = "sensor.pressure_kpa" },
	{ .id = 9, .type = ARBITER_FACT_INT32, .range_min = -500, .range_max = 3000, .default_value = 0, .stale_after_ms = 5000, .safety_relevant = true, .name = "sensor.temp_c" },
	{ .id = 10, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "valve.inlet" },
	{ .id = 11, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "valve.outlet" },
	{ .id = 12, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "valve.reagent" },
	{ .id = 13, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "valve.vent" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 8, .op = ARBITER_OP_GT, .value = 15000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 9, .op = ARBITER_OP_GT, .value = 2000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 4, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_GE, .value = 80, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 2, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_GE, .value = 90, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 3, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 6, .op = ARBITER_OP_GT, .value = 30000, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 3, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 2, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 4, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 7, .op = ARBITER_OP_LE, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 8, .op = ARBITER_OP_LT, .value = 1100, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = true, .name = "close_all_valves" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "close_inlet_open_reagent" },
	{ .id = 2, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "close_outlet_open_vent" },
	{ .id = 3, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "close_reagent" },
	{ .id = 4, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 50, .safe_state_action = true, .name = "emergency_cool" },
	{ .id = 5, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 10, .safe_state_action = true, .name = "emergency_vent" },
	{ .id = 6, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "open_inlet" },
	{ .id = 7, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "open_outlet" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 0, .condition_count = 1, .action_start = 5, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 6, .safety_critical = true, .name = "01_safety.overpressure", .explanation = "Pressure > 1500 kPa — emergency vent." },
	{ .id = 1, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 1, .condition_count = 1, .action_start = 4, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 7, .safety_critical = true, .name = "02_safety.overtemp", .explanation = "Temperature > 200°C — emergency cooling." },
	{ .id = 2, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 2, .condition_count = 1, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = true, .name = "03_safety.abort", .explanation = "Operator abort — close all valves." },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 3, .condition_count = 3, .action_start = 6, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 4, .safety_critical = false, .name = "10_seq.start", .explanation = "Sequence started — open inlet valve, begin fill." },
	{ .id = 4, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 6, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "11_seq.fill_check", .explanation = "Fill reached 80% — ready for reagent." },
	{ .id = 5, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 8, .condition_count = 2, .action_start = 1, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = false, .name = "12_seq.add_reagent", .explanation = "Close inlet, open reagent valve." },
	{ .id = 6, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 10, .condition_count = 2, .action_start = 3, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 8, .safety_critical = false, .name = "13_seq.react", .explanation = "Reagent added — begin reaction hold." },
	{ .id = 7, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 12, .condition_count = 2, .action_start = 0, .action_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "14_seq.reaction_timer", .explanation = "Reaction hold > 30s — reaction complete." },
	{ .id = 8, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 14, .condition_count = 2, .action_start = 7, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = false, .name = "15_seq.drain", .explanation = "Begin drain — open outlet valve." },
	{ .id = 9, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 16, .condition_count = 2, .action_start = 2, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 9, .safety_critical = false, .name = "16_seq.drain_check", .explanation = "Drained — close outlet, open vent." },
	{ .id = 10, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 18, .condition_count = 2, .action_start = 0, .action_count = 1, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "17_seq.complete", .explanation = "Pressure vented — sequence complete." },
};

static const char *model_mode_names[] = {
	"mode.abort",
	"mode.add_reagent",
	"mode.complete",
	"mode.drain",
	"mode.fill",
	"mode.idle",
	"mode.overpressure",
	"mode.overtemp",
	"mode.react",
	"mode.vent",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "valve_sequencer",
	.model_hash = { 0x28, 0x13, 0xd2, 0x36, 0x26, 0xbf, 0x1f, 0xa2, 0xeb, 0xcb, 0x7f, 0x98, 0xa1, 0x0b, 0x6c, 0xa1, 0x94, 0x6e, 0x91, 0xc2, 0x13, 0x61, 0x04, 0x43, 0xc3, 0x1d, 0xcf, 0x46, 0x34, 0xae, 0x92, 0x17 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 14,
	.rule_count = 11,
	.condition_count = 20,
	.action_count = 8,
	.mode_count = 10,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.mode_names = model_mode_names,
};
