/* SPDX-License-Identifier: MIT */
/* AUTO-GENERATED by arbiterc — do not edit */

#include "arbiter_model.h"
#include <arbiter/arbiter.h>

static const struct ARBITER_fact_def model_facts[] = {
	{ .id = 0, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "budget.overcommit" },
	{ .id = 1, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "budget.remaining" },
	{ .id = 2, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "budget.total_demand" },
	{ .id = 3, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 100, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "in.battery_pct" },
	{ .id = 4, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 50000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = true, .name = "in.budget_mw" },
	{ .id = 5, .type = ARBITER_FACT_BOOL, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "in.enable" },
	{ .id = 6, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub0.alloc_mw" },
	{ .id = 7, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 20000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub0.demand_mw" },
	{ .id = 8, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 100, .default_value = 90, .stale_after_ms = 0, .safety_relevant = false, .name = "sub0.priority" },
	{ .id = 9, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub1.alloc_mw" },
	{ .id = 10, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 10000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub1.demand_mw" },
	{ .id = 11, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 100, .default_value = 70, .stale_after_ms = 0, .safety_relevant = false, .name = "sub1.priority" },
	{ .id = 12, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub2.alloc_mw" },
	{ .id = 13, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 15000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub2.demand_mw" },
	{ .id = 14, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 100, .default_value = 40, .stale_after_ms = 0, .safety_relevant = false, .name = "sub2.priority" },
	{ .id = 15, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 0, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub3.alloc_mw" },
	{ .id = 16, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 25000, .default_value = 0, .stale_after_ms = 0, .safety_relevant = false, .name = "sub3.demand_mw" },
	{ .id = 17, .type = ARBITER_FACT_INT32, .range_min = 0, .range_max = 100, .default_value = 95, .stale_after_ms = 0, .safety_relevant = false, .name = "sub3.priority" },
};

static const struct ARBITER_condition_def model_conditions[] = {
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_LT, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 3, .op = ARBITER_OP_GE, .value = 5, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_LE, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 0, .op = ARBITER_OP_GT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 1, .op = ARBITER_OP_LT, .value = 0, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
	{ .fact_id = 5, .op = ARBITER_OP_EQ, .value = 1, .group = ARBITER_COND_ALL, .group_index = 0, .next = UINT16_MAX },
};

static const struct ARBITER_action_def model_actions[] = {
	{ .id = 0, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "apply_power_config" },
	{ .id = 1, .type = ARBITER_ACTION_CALLBACK, .target_fact_id = 0, .target_value = 0, .callback = NULL, .must_complete_within_ms = 0, .safe_state_action = false, .name = "brownout_shutdown" },
};

static const struct ARBITER_rule_def model_rules[] = {
	{ .id = 0, .rule_class = ARBITER_RULE_MODE_GUARD, .condition_start = 0, .condition_count = 1, .action_start = 0, .action_count = 0, .expr_start = 0, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = 1, .safety_critical = false, .name = "01_idle", .explanation = NULL },
	{ .id = 1, .rule_class = ARBITER_RULE_SAFETY_GUARD, .condition_start = 1, .condition_count = 1, .action_start = 1, .action_count = 1, .expr_start = 0, .expr_count = 4, .safety_goal_id = UINT16_MAX, .set_mode = 0, .safety_critical = true, .name = "02_brownout", .explanation = "Battery critical — all loads shed." },
	{ .id = 2, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 2, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 4, .expr_count = 4, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "10_sum_demand", .explanation = NULL },
	{ .id = 3, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 4, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 8, .expr_count = 5, .safety_goal_id = UINT16_MAX, .set_mode = 2, .safety_critical = false, .name = "20_normal", .explanation = "Budget sufficient — full allocation." },
	{ .id = 4, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 6, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 13, .expr_count = 7, .safety_goal_id = UINT16_MAX, .set_mode = 3, .safety_critical = false, .name = "30_shed_display", .explanation = "Over budget — display shed." },
	{ .id = 5, .rule_class = ARBITER_RULE_INFERENCE, .condition_start = 8, .condition_count = 2, .action_start = 0, .action_count = 0, .expr_start = 20, .expr_count = 3, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "31_shed_sensors", .explanation = "Still over budget — sensors also shed." },
	{ .id = 6, .rule_class = ARBITER_RULE_OBLIGATION, .condition_start = 10, .condition_count = 1, .action_start = 0, .action_count = 1, .expr_start = 23, .expr_count = 0, .safety_goal_id = UINT16_MAX, .set_mode = UINT16_MAX, .safety_critical = false, .name = "40_apply", .explanation = "Apply computed power allocations." },
};

static const struct ARBITER_expr_def model_expressions[] = {
	{ .target_fact_id = 6, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 9, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 15, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ADD, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 10, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ADD, .left_fact_id = 2, .left_literal = 0, .right_fact_id = 13, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 2, .op = ARBITER_EXPR_ADD, .left_fact_id = 2, .left_literal = 0, .right_fact_id = 16, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 0, .op = ARBITER_EXPR_SUB, .left_fact_id = 2, .left_literal = 0, .right_fact_id = 4, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 6, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 9, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 10, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 13, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 15, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 16, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_SUB, .left_fact_id = 4, .left_literal = 0, .right_fact_id = 2, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 12, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 6, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 9, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 10, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 15, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 16, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_ADD, .left_fact_id = 7, .left_literal = 0, .right_fact_id = 10, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_ADD, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 16, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_SUB, .left_fact_id = 4, .left_literal = 0, .right_fact_id = 1, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 9, .op = ARBITER_EXPR_ASSIGN, .left_fact_id = 65535, .left_literal = 0, .right_fact_id = 65535, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_SUB, .left_fact_id = 4, .left_literal = 0, .right_fact_id = 7, .right_literal = 0, .scale = 1 },
	{ .target_fact_id = 1, .op = ARBITER_EXPR_SUB, .left_fact_id = 1, .left_literal = 0, .right_fact_id = 16, .right_literal = 0, .scale = 1 },
};

static const char *model_mode_names[] = {
	"mode.brownout",
	"mode.idle",
	"mode.normal",
	"mode.shedding",
};

const struct ARBITER_model ARBITER_generated_model = {
	.name = "power_budget",
	.model_hash = { 0x5c, 0xb6, 0x0b, 0x65, 0xa2, 0x99, 0x7f, 0x0a, 0xe4, 0xeb, 0x16, 0xe0, 0x65, 0xf1, 0xe0, 0x59, 0x86, 0x4d, 0x5f, 0x2b, 0x22, 0xa3, 0xf8, 0xe7, 0xcd, 0x65, 0xd9, 0xcb, 0x4e, 0xdc, 0xd9, 0x48 },
	.schema_hash = { 0x0d, 0x55, 0x33, 0x65, 0xf3, 0x4e, 0x02, 0xf3, 0xf8, 0x94, 0xe8, 0x25, 0xbb, 0x47, 0x86, 0x45, 0xfd, 0x8b, 0x78, 0xb1, 0x27, 0xf5, 0x8c, 0x42, 0xba, 0xbd, 0x80, 0x1f, 0x77, 0x57, 0x1f, 0x35 },
	.fact_count = 18,
	.rule_count = 7,
	.condition_count = 11,
	.action_count = 2,
	.expr_count = 23,
	.mode_count = 4,
	.facts = model_facts,
	.rules = model_rules,
	.conditions = model_conditions,
	.actions = model_actions,
	.expressions = model_expressions,
	.mode_names = model_mode_names,
};
